title: Charles Fucile
description: Aerospace Engineering Portfolio

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://cfucile3.github.io"
baseurl: "/Portfolio"
